# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2096191bccee130fb2474c6dcb0fc9432e94d4fc7143cd7dd66575a0bb11a95068894bad979550257a83fec8d45be7898f59e174c47c81a7f587dcc908041351

test:
  secret_key_base: 810cfae78b73c26b49661ff726c0afa92ca0b49069965ff82cb8d35249c2e387dbb10d6ff5436db6ad696933cd1dcdd53f3109979ea21fb859afae7557762b8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
